-- this tables gonna captures every changes change from kafka topic.

USE ROLE KAFKA_CONNECTOR_ROLE_1;
USE DATABASE CDC_DATABASE;
USE SCHEMA CDC_LANDING;

CREATE TABLE IF NOT EXISTS CUSTOMER_CHANGES (
    CUSTOMER_ID       NUMBER(38, 0),
    FIRST_NAME        VARCHAR,
    LAST_NAME         VARCHAR,
    EMAIL             VARCHAR,
    PHONE_NUMBER      VARCHAR,
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);

CREATE TABLE IF NOT EXISTS SUPPLIER_CHANGES (
    SUPPLIER_ID       NUMBER(38, 0),
    NAME              VARCHAR,
    CONTACT_NAME      VARCHAR,
    CONTACT_EMAIL     VARCHAR,
    CONTACT_PHONE     VARCHAR,
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);

CREATE TABLE IF NOT EXISTS PRODUCT_CHANGES (
    PRODUCT_ID        NUMBER(38, 0),
    NAME              VARCHAR,
    DESCRIPTION       VARCHAR,
    UNIT_PRICE        NUMBER(10, 2),
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);

CREATE TABLE IF NOT EXISTS SALES_INVOICE_CHANGES (
    INVOICE_ID        NUMBER(38, 0),
    CUSTOMER_ID       NUMBER(38, 0),
    INVOICE_DATE      TIMESTAMP_NTZ(3),
    TOTAL_SUM         NUMBER(10, 2),
    TAX_AMOUNT        NUMBER(10, 2),
    STATUS            VARCHAR,
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);

CREATE TABLE IF NOT EXISTS SALES_INVOICE_ITEM_CHANGES (
    ITEM_ID           NUMBER(38, 0),
    INVOICE_ID        NUMBER(38, 0),
    PRODUCT_ID        NUMBER(38, 0),
    QUANTITY          NUMBER(38, 0),
    UNIT_PRICE        NUMBER(10, 2),
    DISCOUNT          NUMBER(10, 2),
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);

CREATE TABLE IF NOT EXISTS PURCHASE_BILL_CHANGES (
    BILL_ID           NUMBER(38, 0),
    SUPPLIER_ID       NUMBER(38, 0),
    BILL_DATE         TIMESTAMP_NTZ(3),
    TOTAL_SUM         NUMBER(10, 2),
    TAX_AMOUNT        NUMBER(10, 2),
    PAID_AMOUNT       NUMBER(10, 2),
    STATUS            VARCHAR,
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);

CREATE TABLE IF NOT EXISTS PURCHASE_BILL_ITEM_CHANGES (
    ITEM_ID           NUMBER(38, 0),
    BILL_ID           NUMBER(38, 0),
    PRODUCT_ID        NUMBER(38, 0),
    QUANTITY          NUMBER(38, 0),
    UNIT_PRICE        NUMBER(10, 2),
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);

CREATE TABLE IF NOT EXISTS INVENTORY_MOVEMENT_CHANGES (
    MOVEMENT_ID       NUMBER(38, 0),
    PRODUCT_ID        NUMBER(38, 0),
    MOVEMENT_TYPE     VARCHAR,
    QUANTITY          NUMBER(38, 0),
    MOVEMENT_DATE     TIMESTAMP_NTZ(3),
    CREATED_AT        TIMESTAMP_NTZ(3),
    UPDATED_AT        TIMESTAMP_TZ(3),
    __OP              VARCHAR,
    __TABLE           VARCHAR,
    __LSN             NUMBER(38, 0),
    __SOURCE_TS_MS    NUMBER(38, 0),
    __DELETED         VARCHAR,
    RECORD_METADATA   VARIANT
);


-- Enabling schema evolution permits newly added source fields to be added automatically.
ALTER TABLE CUSTOMER_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE SUPPLIER_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE PRODUCT_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE SALES_INVOICE_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE SALES_INVOICE_ITEM_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE PURCHASE_BILL_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE PURCHASE_BILL_ITEM_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
ALTER TABLE INVENTORY_MOVEMENT_CHANGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;
