-- Triggered CDC merge tasks.
--
-- One-time prerequisites. ACCOUNTADMIN is used only for these grants; all
-- streams and tasks below remain owned and executed by the connector role.


USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE CDC_WAREHOUSE TO ROLE KAFKA_CONNECTOR_ROLE_1;
GRANT CREATE STREAM, CREATE TASK ON SCHEMA CDC_DATABASE.CDC_LANDING
    TO ROLE KAFKA_CONNECTOR_ROLE_1;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE KAFKA_CONNECTOR_ROLE_1;

USE ROLE KAFKA_CONNECTOR_ROLE_1;
USE WAREHOUSE CDC_WAREHOUSE;
USE DATABASE CDC_DATABASE;
USE SCHEMA CDC_LANDING;

CREATE STREAM IF NOT EXISTS CUSTOMER_CHANGES_STREAM
    ON TABLE CUSTOMER_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS SUPPLIER_CHANGES_STREAM
    ON TABLE SUPPLIER_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS PRODUCT_CHANGES_STREAM
    ON TABLE PRODUCT_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS SALES_INVOICE_CHANGES_STREAM
    ON TABLE SALES_INVOICE_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS SALES_INVOICE_ITEM_CHANGES_STREAM
    ON TABLE SALES_INVOICE_ITEM_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS PURCHASE_BILL_CHANGES_STREAM
    ON TABLE PURCHASE_BILL_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS PURCHASE_BILL_ITEM_CHANGES_STREAM
    ON TABLE PURCHASE_BILL_ITEM_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS INVENTORY_MOVEMENT_CHANGES_STREAM
    ON TABLE INVENTORY_MOVEMENT_CHANGES
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE TASK MERGE_CUSTOMER_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.CUSTOMER_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.CUSTOMER AS target
USING (
    SELECT
        CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER,
        CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM CUSTOMER_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CUSTOMER_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.CUSTOMER_ID = source.CUSTOMER_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    FIRST_NAME = source.FIRST_NAME,
    LAST_NAME = source.LAST_NAME,
    EMAIL = source.EMAIL,
    PHONE_NUMBER = source.PHONE_NUMBER,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, CREATED_AT, UPDATED_AT
) VALUES (
    source.CUSTOMER_ID, source.FIRST_NAME, source.LAST_NAME, source.EMAIL,
    source.PHONE_NUMBER, source.CREATED_AT, source.UPDATED_AT
);

CREATE OR REPLACE TASK MERGE_SUPPLIER_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.SUPPLIER_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.SUPPLIER AS target
USING (
    SELECT
        SUPPLIER_ID, NAME, CONTACT_NAME, CONTACT_EMAIL, CONTACT_PHONE,
        CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM SUPPLIER_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SUPPLIER_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.SUPPLIER_ID = source.SUPPLIER_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    NAME = source.NAME,
    CONTACT_NAME = source.CONTACT_NAME,
    CONTACT_EMAIL = source.CONTACT_EMAIL,
    CONTACT_PHONE = source.CONTACT_PHONE,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    SUPPLIER_ID, NAME, CONTACT_NAME, CONTACT_EMAIL, CONTACT_PHONE, CREATED_AT, UPDATED_AT
) VALUES (
    source.SUPPLIER_ID, source.NAME, source.CONTACT_NAME, source.CONTACT_EMAIL,
    source.CONTACT_PHONE, source.CREATED_AT, source.UPDATED_AT
);

CREATE OR REPLACE TASK MERGE_PRODUCT_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.PRODUCT_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.PRODUCT AS target
USING (
    SELECT
        PRODUCT_ID, NAME, DESCRIPTION, UNIT_PRICE, CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM PRODUCT_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY PRODUCT_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.PRODUCT_ID = source.PRODUCT_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    NAME = source.NAME,
    DESCRIPTION = source.DESCRIPTION,
    UNIT_PRICE = source.UNIT_PRICE,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    PRODUCT_ID, NAME, DESCRIPTION, UNIT_PRICE, CREATED_AT, UPDATED_AT
) VALUES (
    source.PRODUCT_ID, source.NAME, source.DESCRIPTION, source.UNIT_PRICE,
    source.CREATED_AT, source.UPDATED_AT
);

CREATE OR REPLACE TASK MERGE_SALES_INVOICE_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.SALES_INVOICE_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.SALES_INVOICE AS target
USING (
    SELECT
        INVOICE_ID, CUSTOMER_ID, INVOICE_DATE, TOTAL_SUM, TAX_AMOUNT,
        STATUS, CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM SALES_INVOICE_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY INVOICE_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.INVOICE_ID = source.INVOICE_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    CUSTOMER_ID = source.CUSTOMER_ID,
    INVOICE_DATE = source.INVOICE_DATE,
    TOTAL_SUM = source.TOTAL_SUM,
    TAX_AMOUNT = source.TAX_AMOUNT,
    STATUS = source.STATUS,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    INVOICE_ID, CUSTOMER_ID, INVOICE_DATE, TOTAL_SUM, TAX_AMOUNT,
    STATUS, CREATED_AT, UPDATED_AT
) VALUES (
    source.INVOICE_ID, source.CUSTOMER_ID, source.INVOICE_DATE, source.TOTAL_SUM,
    source.TAX_AMOUNT, source.STATUS, source.CREATED_AT, source.UPDATED_AT
);

CREATE OR REPLACE TASK MERGE_SALES_INVOICE_ITEM_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.SALES_INVOICE_ITEM_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.SALES_INVOICE_ITEM AS target
USING (
    SELECT
        ITEM_ID, INVOICE_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT,
        CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM SALES_INVOICE_ITEM_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ITEM_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.ITEM_ID = source.ITEM_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    INVOICE_ID = source.INVOICE_ID,
    PRODUCT_ID = source.PRODUCT_ID,
    QUANTITY = source.QUANTITY,
    UNIT_PRICE = source.UNIT_PRICE,
    DISCOUNT = source.DISCOUNT,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    ITEM_ID, INVOICE_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT,
    CREATED_AT, UPDATED_AT
) VALUES (
    source.ITEM_ID, source.INVOICE_ID, source.PRODUCT_ID, source.QUANTITY,
    source.UNIT_PRICE, source.DISCOUNT, source.CREATED_AT, source.UPDATED_AT
);

CREATE OR REPLACE TASK MERGE_PURCHASE_BILL_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.PURCHASE_BILL_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.PURCHASE_BILL AS target
USING (
    SELECT
        BILL_ID, SUPPLIER_ID, BILL_DATE, TOTAL_SUM, TAX_AMOUNT, PAID_AMOUNT,
        STATUS, CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM PURCHASE_BILL_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY BILL_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.BILL_ID = source.BILL_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    SUPPLIER_ID = source.SUPPLIER_ID,
    BILL_DATE = source.BILL_DATE,
    TOTAL_SUM = source.TOTAL_SUM,
    TAX_AMOUNT = source.TAX_AMOUNT,
    PAID_AMOUNT = source.PAID_AMOUNT,
    STATUS = source.STATUS,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    BILL_ID, SUPPLIER_ID, BILL_DATE, TOTAL_SUM, TAX_AMOUNT, PAID_AMOUNT,
    STATUS, CREATED_AT, UPDATED_AT
) VALUES (
    source.BILL_ID, source.SUPPLIER_ID, source.BILL_DATE, source.TOTAL_SUM,
    source.TAX_AMOUNT, source.PAID_AMOUNT, source.STATUS,
    source.CREATED_AT, source.UPDATED_AT
);

CREATE OR REPLACE TASK MERGE_PURCHASE_BILL_ITEM_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.PURCHASE_BILL_ITEM_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.PURCHASE_BILL_ITEM AS target
USING (
    SELECT
        ITEM_ID, BILL_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM PURCHASE_BILL_ITEM_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ITEM_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.ITEM_ID = source.ITEM_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    BILL_ID = source.BILL_ID,
    PRODUCT_ID = source.PRODUCT_ID,
    QUANTITY = source.QUANTITY,
    UNIT_PRICE = source.UNIT_PRICE,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    ITEM_ID, BILL_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, CREATED_AT, UPDATED_AT
) VALUES (
    source.ITEM_ID, source.BILL_ID, source.PRODUCT_ID, source.QUANTITY,
    source.UNIT_PRICE, source.CREATED_AT, source.UPDATED_AT
);

CREATE OR REPLACE TASK MERGE_INVENTORY_MOVEMENT_CHANGES_TASK
    WAREHOUSE = CDC_WAREHOUSE
    WHEN SYSTEM$STREAM_HAS_DATA('CDC_DATABASE.CDC_LANDING.INVENTORY_MOVEMENT_CHANGES_STREAM')
AS
MERGE INTO CDC_DATABASE.RAW_DATA.INVENTORY_MOVEMENT AS target
USING (
    SELECT
        MOVEMENT_ID, PRODUCT_ID, MOVEMENT_TYPE, QUANTITY,
        MOVEMENT_DATE, CREATED_AT, UPDATED_AT,
        (__OP = 'd' OR COALESCE(TRY_TO_BOOLEAN(__DELETED), FALSE)) AS IS_DELETED
    FROM INVENTORY_MOVEMENT_CHANGES_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY MOVEMENT_ID
        ORDER BY __LSN DESC NULLS LAST, __SOURCE_TS_MS DESC NULLS LAST
    ) = 1
) AS source
ON target.MOVEMENT_ID = source.MOVEMENT_ID
WHEN MATCHED AND source.IS_DELETED THEN DELETE
WHEN MATCHED AND NOT source.IS_DELETED THEN UPDATE SET
    PRODUCT_ID = source.PRODUCT_ID,
    MOVEMENT_TYPE = source.MOVEMENT_TYPE,
    QUANTITY = source.QUANTITY,
    MOVEMENT_DATE = source.MOVEMENT_DATE,
    CREATED_AT = source.CREATED_AT,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED AND NOT source.IS_DELETED THEN INSERT (
    MOVEMENT_ID, PRODUCT_ID, MOVEMENT_TYPE, QUANTITY,
    MOVEMENT_DATE, CREATED_AT, UPDATED_AT
) VALUES (
    source.MOVEMENT_ID, source.PRODUCT_ID, source.MOVEMENT_TYPE,
    source.QUANTITY, source.MOVEMENT_DATE, source.CREATED_AT, source.UPDATED_AT
);

-- CREATE OR REPLACE leaves tasks suspended. Resume every task after all task
-- definitions have been created successfully.
ALTER TASK MERGE_CUSTOMER_CHANGES_TASK RESUME;
ALTER TASK MERGE_SUPPLIER_CHANGES_TASK RESUME;
ALTER TASK MERGE_PRODUCT_CHANGES_TASK RESUME;
ALTER TASK MERGE_SALES_INVOICE_CHANGES_TASK RESUME;
ALTER TASK MERGE_SALES_INVOICE_ITEM_CHANGES_TASK RESUME;
ALTER TASK MERGE_PURCHASE_BILL_CHANGES_TASK RESUME;
ALTER TASK MERGE_PURCHASE_BILL_ITEM_CHANGES_TASK RESUME;
ALTER TASK MERGE_INVENTORY_MOVEMENT_CHANGES_TASK RESUME;
